; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_f411re]
platform = ststm32
board = nucleo_f411re
framework = stm32cube

lib_deps = 
    FreeRTOS
lib_ignore =
    eigen

build_flags =
  -mfpu=fpv4-sp-d16
  -mfloat-abi=softfp
  -DF4
  -D DEV 
  -I lib/FreeRTOS/include
  -I lib/FreeRTOS/CMSIS_RTOS_V2
  -I lib/FreeRTOS/portable/GCC/ARM_CM4F
  -Ilib/eigen
  -Iinclude

lib_archive = no
lib_ldf_mode = deep+

check_tool = clangtidy, cppcheck

check_src_filters =
    +<src/**>
    -<lib/**>
    -<.pio/**>
    -<lib/FreeRTOS/include/*>
    -<lib/FreeRTOS/CMSIS_RTOS_V2/*>
    -<lib/FreeRTOS/portable/GCC/ARM_CM4F/*>
    -<lib/eigen/*>

check_flags =
    clangtidy: --config-file=../.clang-tidy
    cppcheck: --enable=all
    cppcheck: --addon=misra
    cppcheck: --inline-suppr
    cppcheck: --suppressions-list=cppcheck.suppress
    cppcheck: --showtime=file-total 
    cppcheck: --inconclusive
    cppcheck: --force
    cppcheck: src lib/braiteoiri/include lib/comheadan/include

[env:stm32f072c8t6]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

lib_deps = 
    FreeRTOS
lib_ignore =
    eigen

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D DEV 
  -D STM
  -D F0
  -I lib/FreeRTOS/include
  -I lib/FreeRTOS/CMSIS_RTOS_V2_f0
  -I lib/FreeRTOS/portable/GCC/ARM_CM0 
  -Ilib/eigen
  -Iinclude
  -Wl,-Map=.pio/build/memory.map

build_src_filter =
    +<main.cpp>
    -<platform/*>
    +<platform/stm_f0.cpp>
    -<tools/*>

lib_archive = no
lib_ldf_mode = deep+

check_tool = clangtidy, cppcheck

check_src_filters =
    +<src/**>
    -<lib/**>
    -<.pio/**>
    -<lib/FreeRTOS/include/*>
    -<lib/FreeRTOS/CMSIS_RTOS_V2/*>
    -<lib/FreeRTOS/portable/GCC/ARM_CM4F/*>
    -<lib/eigen/*>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_sensor_flash_demo]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

lib_deps =
    FreeRTOS
lib_ignore =
    eigen

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D DEV
  -D STM
  -D F0
  -I lib/FreeRTOS/include
  -I lib/FreeRTOS/CMSIS_RTOS_V2_f0
  -I lib/FreeRTOS/portable/GCC/ARM_CM0
  -Ilib/eigen
  -Iinclude

build_src_filter =
    -<*>
    +<sensor_flash_demo.cpp>
    +<platform/stm_f0.cpp>

lib_archive = no
lib_ldf_mode = deep+

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_sensor_csv_demo]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

lib_deps =
    FreeRTOS
lib_ignore =
    eigen

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D DEV
  -D STM
  -D F0
  -I lib/FreeRTOS/include
  -I lib/FreeRTOS/CMSIS_RTOS_V2_f0
  -I lib/FreeRTOS/portable/GCC/ARM_CM0
  -Ilib/eigen
  -Iinclude

build_src_filter =
    -<*>
    +<sensor_csv_demo.cpp>
    +<platform/stm_f0.cpp>

lib_archive = no
lib_ldf_mode = deep+

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_flash_scope]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<flash_scope_demo.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_spi_bare_probe]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<spi_bare_probe.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_spi_line_clamp_probe]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<spi_line_clamp_probe.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_spi_gpio_selftest]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<spi_gpio_selftest.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_spi_gpio_selftest_bme_boot_low]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0
  -D BME680_CS_BOOT_LOW

build_src_filter =
    -<*>
    +<spi_gpio_selftest.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_bme680_mode_probe]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<bme680_mode_probe.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_bme680_mode_probe_boot_low]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0
  -D BME680_CS_BOOT_LOW

build_src_filter =
    -<*>
    +<bme680_mode_probe.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_rescue]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<rescue.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_rescue_under_reset]
platform = ststm32
board = stm32f072c8t6_under_reset
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<rescue.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_alive]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<alive.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_alive_under_reset]
platform = ststm32
board = stm32f072c8t6_under_reset
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<alive.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_buzzer]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<buzzer_demo.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_buzzer_gpio]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<buzzer_gpio.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_pb0_raw]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<pb0_raw.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_pb0_tone_raw]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<pb0_tone_raw.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

[env:stm32f072c8t6_pb0_tone_raw_under_reset]
platform = ststm32
board = stm32f072c8t6_under_reset
framework = stm32cube

build_flags =
  -DSTM32F072xB
  -D STM32F0
  -D STM
  -D F0

build_src_filter =
    -<*>
    +<pb0_tone_raw.cpp>

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200


[env:sil]
platform = native
test_build_src = yes

lib_extra_dirs = src
lib_ignore =
    eigen
    MPU6050
    BMP390
    braiteoiri
    comheadan

build_src_filter =
    +<src/fsm.cpp>
    +<src/tools/kalman_filter.cpp>
    +<src/tools/state_machine.cpp>
    +<src/**>
    +<test/**>
    +<lib/braiteoiri/src/IMU/IMU.cpp>      
    +<lib/braiteoiri/src/Baro/baro.cpp> 
    -<lib/braiteoiri/src/IMU/MPU6050/*>
    -<lib/braiteoiri/src/Baro/BMP390/*>
    -<lib/comheadan/src/SPI/*>
    -<lib/comheadan/src/I2C/*>
    -<lib/eigen/bench*>

lib_archive = no

build_flags = 
    -std=gnu++17
    -DUNIT_TEST
    -Ilib/eigen
    -Ilib/braiteoiri/include/
    -Ilib/comheadan/include/
    -Iinclude
