; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_f411re]
platform = ststm32
board = nucleo_f411re
framework = stm32cube

check_tool = clangtidy, cppcheck

check_src_filters =
  +<src/>
  -<lib/>
  -<.pio/>
  -<include/>

check_flags =
  clangtidy: --config-file=../.clang-tidy
  cppcheck: --platform=arm32-wchar_t4
  cppcheck: --enable=warning,style,performance,portability
  cppcheck: --addon=misra
  cppcheck: --inline-suppr
  cppcheck: --suppressions-list=cppcheck.suppress
  cppcheck: --showtime=file-total

lib_deps = 
    FreeRTOS
    eigen/Eigen@^3.4.0
    
build_flags =
  -mfpu=fpv4-sp-d16
  -mfloat-abi=softfp
  -DF4
  -D DEV 

  -I lib/FreeRTOS/include
  -I lib/FreeRTOS/CMSIS_RTOS_V2
  -I lib/FreeRTOS/portable/GCC/ARM_CM4F
  -Iinclude

lib_archive = no

lib_ldf_mode = deep+

[env:sil]
platform = native
build_flags = -std=gnu++17

check_tool = clangtidy, cppcheck

check_src_filters =
  +<src/>
  -<lib/>
  -<.pio/>
  -<include/>

check_flags =
  clangtidy: --config-file=../.clang-tidy
  cppcheck: --platform=arm32-wchar_t4
  cppcheck: --enable=warning,style,performance,portability
  cppcheck: --addon=misra
  cppcheck: --inline-suppr
  cppcheck: --suppressions-list=cppcheck.suppress
  cppcheck: --showtime=file-total
  cppcheck: --rule-texts=rules.txt
